version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: area-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - area-network

  frontend-web:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    container_name: area-frontend-web
    ports:
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - area-network

networks:
  area-network:
    driver: bridge