# fly.toml app configuration file generated for discord-bot-area on 2025-12-10T09:21:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-bot-area"
primary_region = "cdg"

[build]

[processes]
  app = "node index.js"

[deploy]
  strategy = "immediate"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1