name: area_mobile
description: Mobile frontend for AREA (Flutter)
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.6.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.20.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
